name: Build and Release Egyptian Exchange Stocks
# GitHub Actions workflow for building and releasing The Egyptian Exchange desktop application

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        include:
          - os: windows-latest
            arch: x64
            target: win
          - os: windows-latest
            arch: ia32
            target: win
          - os: macos-latest
            arch: x64
            target: mac
          - os: ubuntu-latest
            arch: x64
            target: linux
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build application
      run: npm run publish
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Egyptian-Exchange-Stocks-${{ matrix.target }}-${{ matrix.arch }}-${{ github.sha }}
        path: dist/
        
  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts/
        
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          artifacts/*/Egyptian-Exchange-Stocks-*.exe
          artifacts/*/Egyptian-Exchange-Stocks-*.dmg
          artifacts/*/Egyptian-Exchange-Stocks-*.AppImage
          artifacts/*/Egyptian-Exchange-Stocks-*.deb
          artifacts/*/Egyptian-Exchange-Stocks-*.rpm
        generate_release_notes: true
        draft: false
        prerelease: false
        tag_name: ${{ github.ref_name }}
        name: Egyptian Exchange Stocks ${{ github.ref_name }}
        body: |
          ## Egyptian Exchange Stocks Desktop Application
          
          This release contains the Egyptian Exchange Stocks desktop application for all supported platforms.
          
          ### Features
          - Real-time stock data from Egyptian Exchange
          - Cross-platform desktop application (Windows 32-bit, Windows 64-bit, macOS, Linux)
          - Egyptian Exchange market data tracking
          - Automatic updates support
          - Column visibility customization
          - Watchlist functionality
          
          ### Installation
          Download the appropriate installer for your operating system and architecture:
          
          **Windows:**
          - `Egyptian-Exchange-Stocks-*-win-ia32.exe` - Windows 32-bit
          - `Egyptian-Exchange-Stocks-*-win-x64.exe` - Windows 64-bit
          
          **macOS:**
          - `Egyptian-Exchange-Stocks-*-mac-x64.dmg` - macOS Intel
          
          **Linux:**
          - `Egyptian-Exchange-Stocks-*-linux-x64.AppImage` - Linux AppImage
          - `Egyptian-Exchange-Stocks-*-linux-x64.deb` - Debian/Ubuntu package
          - `Egyptian-Exchange-Stocks-*-linux-x64.rpm` - Red Hat/Fedora package
          
          ### Auto-Updates
          This application supports automatic updates. Updates will be checked when the app starts and can be configured in the settings.
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
